name: Go
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [ "1.16", "1.17", "1.18" ]
        goos: [ "linux", "darwin", "windows" ]
        goarch: [ "amd64", "386", "arm64", "arm" ]
        include:
        - goos: "linux"
          os: "ubuntu-latest"
        - goos: "darwin"
          os: "macos-latest"
        - goos: "windows"
          os: "windows-latest"
        exclude:
        - goos: "darwin"
          goarch: "386"
        - goos: "darwin"
          goarch: "arm"
    runs-on: ${{ matrix.os }}
    env:
      goos: ${{ matrix.goos }}
      goarch: ${{ matrix.arch }}
    steps:
    - name: setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: checkout
      uses: actions/checkout@v2
    - name: test
      run: |
        make test
  ycat:
    name: ycat
    runs-on: ubuntu-latest
    steps:
      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          make ycat/build
      - name: run
        run: |
          ./ycat .github/workflows/go.yml

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: checkout
        uses: actions/checkout@v2
      - name: measure coverage
        run: |
          make cover
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          verbose: true
